baseurl:  "https://luriechildrensbioinformatics.github.io/introR"
publishDir: "docs"
languageCode: en-us
title: Intro to R
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
enableGitInfo: true

permalinks:
  post: /:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Instructors"
      url: "/instructors/"
      weight: 2
    - name: "Syllabus"
      url: "https://github.com/LurieChildrensBioinformatics/introR/blob/main/syllabus.pdf"
      weight: 3
    - name: "Material"
      url: "/material/"
      weight: 4
    - name: "Repo"
      url: "https://github.com/LurieChildrensBioinformatics/introR/"
      weight: 5
    - name: "Resources"
      url: "/resources"
      weight: 6

params:
  description: "Summer 2023 Intro to R course."
  footer: "Powered by [Hugo](https://gohugo.io/), [blogdown](https://github.com/rstudio/blogdown) and [the Ivy theme](https://github.com/yihui/hugo-ivy)"
  highlightjsLang: ["latex", "r", "yaml"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
